ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER Team3 IDENTIFIED BY 123456;

ALTER USER Team3 DEFAULT TABLESPACE users;

ALTER USER Team3 QUOTA UNLIMITED ON users;

GRANT connect, resource TO Team3;


